#!/command/with-contenv sh
# shellcheck shell=sh

set -eu

echo "[INIT-ADDUSER] Starting init-adduser script..."

PUID=${PUID:-912}
PGID=${PGID:-912}

groupmod --non-unique --gid "$PGID" nordvpn
usermod --non-unique --uid "$PUID" nordvpn

echo "[INIT-ADDUSER] init-adduser script completed successfully"
exit 0
