#!/command/with-contenv sh
# shellcheck shell=sh

set -eu

echo "Setup crond service"

cron_dir="/var/spool/cron/crontabs"
cron_file="$cron_dir/root"

rm -f "$cron_file"
touch "$cron_file"

if [ -n "${RECREATE_VPN_CRON:-}" ]; then
    echo "Create reconnection cron"
    echo "$RECREATE_VPN_CRON vpn-reconnect" >> "$cron_file"
fi

if [ -n "${CHECK_CONNECTION_CRON:-}" ]; then
    echo "Create connectivity check cron"
    echo "$CHECK_CONNECTION_CRON vpn-healthcheck" >> "$cron_file"
fi

exit 0
