#!/command/with-contenv sh
# shellcheck shell=sh

set -eu

echo "[INIT-SETUPCRON] Starting init-setupcron script..."

cron_dir="/var/spool/cron/crontabs"
cron_file="$cron_dir/root"

rm -f "$cron_file"
touch "$cron_file"

if [ -n "${RECREATE_VPN_CRON:-}" ]; then
    echo "$RECREATE_VPN_CRON vpn-reconnect" >> "$cron_file"
else
    echo "[INIT-SETUPCRON] No VPN reconnection cron specified"
fi

if [ -n "${CHECK_CONNECTION_CRON:-}" ]; then
    echo "$CHECK_CONNECTION_CRON vpn-healthcheck" >> "$cron_file"
else
    echo "[INIT-SETUPCRON] No VPN health check cron specified"
fi

echo "[INIT-SETUPCRON] init-setupcron script completed successfully"
exit 0
