#!/command/with-contenv sh
# shellcheck shell=sh

set -eu

echo "[INIT-CREATEVPNCONFIG] Starting init-createvpnconfig script..."

vpn-config

echo "[INIT-CREATEVPNCONFIG] init-createvpnconfig script completed successfully"
exit 0
