#!/command/with-contenv sh
# shellcheck shell=sh

set -eu

echo "[SERVICE-NORDVPND] Stopping nordvpnd service..."

. /usr/local/bin/backend-functions

echo "[SERVICE-NORDVPND] Cleaning VPN pinhole..."
run4 -F VPN-SERVER

echo "[SERVICE-NORDVPND] Disconnecting OpenVPN cleanly..."
echo "signal SIGTERM" | nc 127.0.0.1 7505
sleep 5

echo "[SERVICE-NORDVPND] nordvpnd service stopped successfully"
exit 0
