#!/command/with-contenv sh
# shellcheck shell=sh

set -eu

authfile="/tmp/auth"

echo "Create auth file"

echo "$USER" > "$authfile"
echo "$PASS" >> "$authfile"
chmod 0600 "$authfile"
chown nordvpn:nordvpn "$authfile"

exit 0
