#!/command/with-contenv sh
# shellcheck shell=sh

set -eu

echo "[INIT-CREATEAUTH] Starting init-createauth script..."

authfile="/run/xt/auth"

echo "$USER" > "$authfile"
echo "$PASS" >> "$authfile"
chmod 0600 "$authfile"
chown nordvpn:nordvpn "$authfile"

echo "[INIT-CREATEAUTH] init-createauth script completed successfully"
exit 0
