name: Update Dockerfile

on:
  push:
  schedule:
    - cron: 0 3 * * *

jobs:
  dockerfile_updater:
    name: Update Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Update Dockerfiles
        uses: ludeeus/dockerfile-updater@21.01.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
